module.exports = {
  feet: 'feet',
  centimeter: 'cm',
  kilogram: 'kg',
  inches: 'inches',
  stone: 'stone',
  pound: 'pound',
  feetToCmConversionValue: 30.48,
  inchesToCmConversionValue: 2.54,
  stoneToKgConversionValue: 6.35029,
  poundToKgConversionValue: 0.45359237,
  kgToLbConversionValue: 2.20462,
  noPatientFound: 'No Patient data found!',
  patientFamilyDelete: 'Family Details Removed successfully!',
  patientAllergyDelete: 'Patient Allergy Removed successfully!',
  updatedPreference: 'Prefernece Updated successfully.!',
  success: 'Success',
  nameExists: 'Name already exists',
  noDoctorFound: 'No doctor found',
  tenantsUpdatemessage: 'Tenants updated successfully.!',
  caseAdded: 'Case Added successfully.!',
  conditionAdded: 'Medical Condition Added successfully.!',
  relationAdded: 'Relation Added successfully.!',
  norelation: 'No relation Found',
  allergiesAdded: 'Allergies Added successfully.!',
  emptyAllergies: 'Allergies Name Cannot Be Empty!',
  emptyFAQ: 'FAQ Questions or Answer Cannot Be Empty!',
  noFAQ: 'No FAQ found',
  addedFAQ: 'FAQ Added',
  emptyReaction: 'Reaction Name Cannot Be Empty!',
  emptyMedication: 'Medication Name Cannot Be Empty!',
  reactionAdded: 'Reaction Added successfully.!',
  medicationAdded: 'Medication Added successfully.!',
  patientAllergyAdd: 'Patient Allergies Added',
  noAllergies: 'No Allergies found',
  noCondition: 'No MedicalCondition found',
  noMedication: 'No Medication found',
  noReaction: 'No Reaction Found',
  updateAllergies: 'Allergies updated',
  familyDetailsAdd: 'Family Details Allegies Added',
  familyDetailsUpdate: 'Family Details updated',
  conditionAlreadyExists: 'condition already exists',
  insuranceProviderAlreadyExists: 'insurance provider already exists',
  insurancePlanAlreadyExists: 'insurance plan already exists',
  patientMedicationAdded: 'Patient Medication added',
  patientMedicationUpdated: 'Patient Medication updated',
  patientMedicationDeleted: 'Patient Medication deleted',
  patientMedicalAdded: 'Patient Medical Condition added',
  patientMedicalUpdated: 'Patient Medical Condition updated',
  patientMedicalDeleted: 'Patient Medical Condition deleted',
  userNotFound: 'User not found',
  checkEmailAndOpenLink:
    'Check your email and open the link we sent to continue',
  linkExpired: 'Link has expired',
  passwordDoNotMatch: 'Please provide strong password',
  updatedTherapeuticAreas: 'Therapeutic Areas Updated successfully.!',
  newTrial: 'New Trial',
  activeTrial: 'Active Trial',
  trialInvited: 'Trial Invited',
  newTrialInvitation: 'New Trial Invitation',
  newTrialInitiated: 'A new trial has been initiated from the researcher',
  inviteSent:
    'Your invite has been sent and your family member will be notified. The status of their account will be pending until they give you access.',
  updateAccessSettings: 'Access Settings Updated!',
  eighteenYears: 18,
  verifyEmailSubject: 'Whyze Health - Verify your email',
  verifyEmailBody:
    'To sign in your Whyze Health account, you need to verify this new email address.',
  setupPassword: 'setup-password',
  accountDeleted: 'Account deleted !',
  accountRemoved: 'Account Removed!',
  alreadyHaveAccess: 'The User Already Share their account',
  giveCorrectRelationShip: 'Please give correct RelationShip!',
  alreadyLinkVerfied: 'Link request not found or already accepted',
  fieldMissing: 'Some fields are missing',
  userVerfied: 'Your Account Was verified!',
  accountCreated: 'Created',
  accountShared: 'Sharing',
  accountJoined: 'Joined',
  sharingAccessAccount: 'Sharing access to your account',
  inviteSend: 'Invite Send',
  newAccountTrue: 'true',
  newAccountfalse: 'false',
  someEmailMissing: 'You don`t have the permission to access this account!',
  emailMismatch:
    'Emails do not match, or the invitation has not been accepted, or the accounts are not linked!',
  tokenNeed: 'Token needed',
  notAvailable: 'N/A',
  accountVerified: 'Your account was verified!',
  sentAccessSharingInvite: 'Your invitation has been sent to the guardian',
  sharedAccount: 'shared_account',
  sharingAccessRemoved: 'Removed Sharing access!',
  successInviteSent: 'Invite sent successfully!',
  callBackRequest: 'Request call back to arrange',
  accepted: 'Accepted',
  callBack: 'Call back request',
  profileUploadSuccessfully: 'Profile upload successfully!',
};
