module.exports = {
  patient: 'patient',
  hcp: 'hcp',
  whyzeAdmin: 'whyze_admin',
  hospitalAdmin: 'hospital_admin',
  hospitalGroupAdmin: 'hospital_group_admin',
  researchAssistant: 'research_assistant',
  primaryInvestigator: 'primary_investigator',
  adminRoleCheck: [
    'whyze_admin',
    'hospital_admin',
    'hospital_group_admin',
    'research_assistant',
    'primary_investigator',
  ],
  patientRoleCheck: ['patient'],
  memberOrganiser: 'member_organizer',
  member: 'member',
  accountOwner: 'account_owner',
  sharedAccount: 'shared_account',
  receivedAccount: 'received_account',
  singleHospital: 'singleHospital',
  hospitalGroup: 'hospitalGroup',
  researchOrganization: 'researchOrganization',
  userModelRoleCheck: [
    'patient',
    'hcp',
    'hospital_admin',
    'hospital_group_admin',
    'research_assistant',
    'primary_investigator',
  ],
};
