module.exports = {
  feet: 'feet',
  centimeter: 'cm',
  kilogram: 'kg',
  inches: 'inches',
  stone: 'stone',
  pound: 'pound',
  feetToCmConversionValue: 30.48,
  inchesToCmConversionValue: 2.54,
  stoneToKgConversionValue: 6.35029,
  poundToKgConversionValue: 0.45359237,
  kgToLbConversionValue: 2.20462,
  noPatientFound: 'No Patient data found!',
  patientFamilyDelete: 'Family Details Removed successfully!',
  patientAllergyDelete: 'Patient Allergy Removed successfully!',
  updatedPreference: 'Prefernece Updated successfully.!',
  success: 'Success',
  nameExists: 'Name already exists',
  noDoctorFound: 'No doctor found',
  tenantsUpdatemessage: 'Tenants updated successfully.!',
  caseAdded: 'Case Added successfully.!',
  conditionAdded: 'Medical Condition Added successfully.!',
  relationAdded: 'Relation Added successfully.!',
  norelation: 'No relation Found',
  allergiesAdded: 'Allergies Added successfully.!',
  emptyAllergies: 'Allergies Name Cannot Be Empty!',
  emptyFAQ: 'FAQ Questions or Answer Cannot Be Empty!',
  noFAQ: 'No FAQ found',
  addedFAQ: 'FAQ Added',
  emptyReaction: 'Reaction Name Cannot Be Empty!',
  emptyMedication: 'Medication Name Cannot Be Empty!',
  reactionAdded: 'Reaction Added successfully.!',
  medicationAdded: 'Medication Added successfully.!',
  patientAllergyAdd: 'Patient Allergies Added',
  noAllergies: 'No Allergies found',
  noCondition: 'No MedicalCondition found',
  noMedication: 'No Medication found',
  noReaction: 'No Reaction Found',
  updateAllergies: 'Allergies updated',
  familyDetailsAdd: 'Family Details Allegies Added',
  familyDetailsUpdate: 'Family Details updated',
  conditionAlreadyExists: 'condition already exists',
  insuranceProviderAlreadyExists: 'insurance provider already exists',
  insurancePlanAlreadyExists: 'insurance plan already exists',
  patientMedicationAdded: 'Patient Medication added',
  patientMedicationUpdated: 'Patient Medication updated',
  patientMedicationDeleted: 'Patient Medication deleted',
  patientMedicalAdded: 'Patient Medical Condition added',
  patientMedicalUpdated: 'Patient Medical Condition updated',
  patientMedicalDeleted: 'Patient Medical Condition deleted',
  userNotFound: 'User not found',
};
